Karanteeni/karanteeni.github.io

index.html
Näytettiin sit boksi näyttään punasta ku servu on kiinni
=> Statusboxi korjattu

index.html
=> 0 => Pelaajia ei ole paikalla

maailmat.html, vendor/js/server-status.js, yllapito.html
Poistettu center tagit (obsolete), korvattu margin autol ja text-align centerillä ylläpito sivuissa
Muutettu karanteeni.net muotoon mc.karanteeni.net
=> Yp + status

vendor/js/jutut.js, yllapito.html
Lisätty Naxray ylläpitoon ^^
Lisätty ylläpitojuttuja
Skinit vaihtuvat nyt automaattisesti (rip persoonalliset asennot :c)
=> Muutamia lisäyksiä

LICENSE.md, README.md
Vaihdoin Unlicensen MITtiin tekijänoikeuksien vuoksi. Readme päivitetty jos joku nyt välttämättä sitä haluaa lukea.
=> Lisenssi + readme

vendor/js/donators.json
=> Lisätty lahjoittajia

assets/components/footer.jsx, assets/components/ranks.jsx, assets/includes/changes.html
=> Muutosloki + parin errorin fixaus

assets/components/ranks.jsx
Koodia muokattu taas sen verran, että rankit ja niiden komentolistat on erikseen.
=> Rankkipäivitys

README.md, altadmin.html, chat-saannot.html, hoks.html, index.html, lahjoitus.html, maailmat.html, muutokset.html, pohja.html, rankit.html, recipes.html, saannot.html, ukk.html, vendor/css/style_minecraft.css, yleistietoa.html, yllapito.html, yphaku.html
Tekniset muutokset:
- Ei muutoksia
Sisältö:
- Ei muutoksia
Ulkoasu:
- Fixattu edellinen patch
- Ylläpidon nimet mustalla
CSS muutokset:
- Lisätty yp class
=> Juuh elikkäs jooh

assets/components/changelog_button.jsx, index.html, vendor/css/style_minecraft.css
Ei teeman muutosta vaan ns. 'quality of life' parannuksia.
- Yp jutut boxin sisältö keskitetty
- Muutoslokinapin (ja muiden samoilla luokilla) 'hienosäätö' helppolukuisuutta ajatellen
- Sivujen taustakuvan skaalaus niin, ettei se toista itseään, vaan peittää sivun.
=> Pienet "tyylibugi" korjaukset

README.md, assets/components/changes.jsx, assets/components/table_ranks.jsx, hoks.html, modules/Donators/donators.json, modules/Operators/operators.js, modules/Operators/operators.json, muutokset.html, rankit.html, vendor/css/style_minecraft.css, yllapito.html
Tekniset muutokset:
- operators.js palauttaa viestin tyhjien ylläpitokorttien sijaan, mikäli ylläpitäjiä kyseiseen kategoriaan ei ole
- Poistettu include(); funktio muutoksista
- Poistettu CommandRow koskien kompassia
Sisältö:
- Lisätty Susse moderaattoriksi
- Joquliinan ja Nallekarhun donatet korjattu oikeiksi
- Poistettu "Hyvä tietää!" osiosta merkinnät koskien Skyblockia, Kananheittoa ja Prisonia
- Poistettu Raihnailta /compass komento (ei ole olemassa)
- Päivitetty ylläpidon kuvaukset (by Jome)
Ulkoasu:
- Korjattu rankkisivun yleisten komentojen collapsen tausta
CSS muutokset:
- Lisätty id queryselector #commands
- Lisätty #commands background sääntö
=> v. 3.6.0 followed by v. 3.6.1

modules/Operators/operators.json
Sisältö:
- Lisätty Naxray ylläpitolistalle
=>  V. 3.14.2

.gitignore, modules/Operators/operators.json, package-lock.json
=> v. 3.14.5 fix

modules/Donators/donators.json
Sisältö:
- Keijon lahjotukseen se summa
=> v 3.15.1 hotfix

404.html, components/changes.jsx, components/faq.jsx, creasaannot.html, dist/changes.js, dist/faq.js, hoks.html, index.html, lahjoitus.html, maailmat.html, modules/Operators/operators.json, muutokset.html, pohja.html, rankit.html, recipes.html, saannot.html, ukk.html, yleistietoa.html, yllapito.html, yphaku.html
Sisältö:
- Päivitetty Ashen yp kuvaus
- Lisätty koodiblockit jokaisen komennon kohdalle
- Päivitetty muutosloki
Tekniset muutokset:
- Muutettu `changes.jsx` ja `faq.jsx` kaikki varatut merkit HTML entiteeteiksi
- Vaihdettu html filujen kieli "en" -> "fi"
=> v. 3.16.13

README.md, components/changes.jsx, dist/changes.js, modules/Operators/operators.json
Sisältö:
- päivitetty muutosloki
- lisätty Iita ylläpitoon
- siirretty Manuzki operaattoriksi
=> v. 3.16.15

README.md, dist/articles.js
Sisältö:
- Päivitetty README
- Fixattu artikkeli
=> v. 4.2.2-hotfix

vendor/css/modern_flat_light.css
Sisältö:
-Korjattu yksittäinen background-color sääntö
=> v. 4.3.1 hotfix

vendor/css/modern_flat_light.css
Sisältö:
- yksi nav css sääntö
joo byhy nää hotfixit loppuu
=> v. 4.3.1 hotfix #2

vendor/css/modern_flat_light.css
Sisältö:
- vika lupaan
- korjattu nav mobiiliväri teemaan
=> v. 4.3.1 hotfix #3

modules/Operators/operators.json
=> v. 4.3.3 hotfix

ominaisuudet.html
Sisältö:
- Lisää komentoja ominaisuuksiin
=> v. 4.3.5 hotfix#2

README.md, vendor/css/flat_dark.css, vendor/css/flat_light.css, vendor/css/index.css, vendor/css/modern_flat_dark.css, vendor/css/modern_flat_light.css, vendor/css/style_minecraft.css, vendor/css/style_nether.css, vendor/css/style_winter.css, yllapito.html
=> v. 4.4.2 finetuning

rankit.html, vendor/css/index.css, vendor/css/modern_flat_dark.css, vendor/css/modern_flat_light.css
=> v. 4.4.1 hotfix tyylit

components/home/serverstatus.tsx, pages/index.tsx, styles/global.css
Sisältö:
- Korjattu server status
=> v. 5.0.3 Loading spinner

components/layout/navbar.tsx, pages/muutokset.tsx, styles/global.css
=> v 5.0.8 hotfix

pages/muutokset.tsx
=> hotfix date

data/operators.json
```
+ vaapukka
+ mvp
- jafarin
```
=> chore: update operators

styles/global.css
avatut linkit ei jää navbarin taakse
=> fix anchors being behind navbar

components/anchor.tsx, pages/saannot.tsx, styles/global.css
ebin homma nyt sääntöjä klikkaamalla urli päivittyy ja sen voi jakaa
=> anchor links for rules page

components/anchor.tsx, pages/saannot.tsx, styles/global.css
=> more intuitive anchor links
